# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_epanet2')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_epanet2')
    _epanet2 = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_epanet2', [dirname(__file__)])
        except ImportError:
            import _epanet2
            return _epanet2
        try:
            _mod = imp.load_module('_epanet2', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _epanet2 = swig_import_helper()
    del swig_import_helper
else:
    import _epanet2
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

EN_ELEVATION = _epanet2.EN_ELEVATION
EN_BASEDEMAND = _epanet2.EN_BASEDEMAND
EN_PATTERN = _epanet2.EN_PATTERN
EN_EMITTER = _epanet2.EN_EMITTER
EN_INITQUAL = _epanet2.EN_INITQUAL
EN_SOURCEQUAL = _epanet2.EN_SOURCEQUAL
EN_SOURCEPAT = _epanet2.EN_SOURCEPAT
EN_SOURCETYPE = _epanet2.EN_SOURCETYPE
EN_TANKLEVEL = _epanet2.EN_TANKLEVEL
EN_DEMAND = _epanet2.EN_DEMAND
EN_HEAD = _epanet2.EN_HEAD
EN_PRESSURE = _epanet2.EN_PRESSURE
EN_QUALITY = _epanet2.EN_QUALITY
EN_SOURCEMASS = _epanet2.EN_SOURCEMASS
EN_INITVOLUME = _epanet2.EN_INITVOLUME
EN_MIXMODEL = _epanet2.EN_MIXMODEL
EN_MIXZONEVOL = _epanet2.EN_MIXZONEVOL
EN_TANKDIAM = _epanet2.EN_TANKDIAM
EN_MINVOLUME = _epanet2.EN_MINVOLUME
EN_VOLCURVE = _epanet2.EN_VOLCURVE
EN_MINLEVEL = _epanet2.EN_MINLEVEL
EN_MAXLEVEL = _epanet2.EN_MAXLEVEL
EN_MIXFRACTION = _epanet2.EN_MIXFRACTION
EN_TANK_KBULK = _epanet2.EN_TANK_KBULK
EN_DIAMETER = _epanet2.EN_DIAMETER
EN_LENGTH = _epanet2.EN_LENGTH
EN_ROUGHNESS = _epanet2.EN_ROUGHNESS
EN_MINORLOSS = _epanet2.EN_MINORLOSS
EN_INITSTATUS = _epanet2.EN_INITSTATUS
EN_INITSETTING = _epanet2.EN_INITSETTING
EN_KBULK = _epanet2.EN_KBULK
EN_KWALL = _epanet2.EN_KWALL
EN_FLOW = _epanet2.EN_FLOW
EN_VELOCITY = _epanet2.EN_VELOCITY
EN_HEADLOSS = _epanet2.EN_HEADLOSS
EN_STATUS = _epanet2.EN_STATUS
EN_SETTING = _epanet2.EN_SETTING
EN_ENERGY = _epanet2.EN_ENERGY
EN_DURATION = _epanet2.EN_DURATION
EN_HYDSTEP = _epanet2.EN_HYDSTEP
EN_QUALSTEP = _epanet2.EN_QUALSTEP
EN_PATTERNSTEP = _epanet2.EN_PATTERNSTEP
EN_PATTERNSTART = _epanet2.EN_PATTERNSTART
EN_REPORTSTEP = _epanet2.EN_REPORTSTEP
EN_REPORTSTART = _epanet2.EN_REPORTSTART
EN_RULESTEP = _epanet2.EN_RULESTEP
EN_STATISTIC = _epanet2.EN_STATISTIC
EN_PERIODS = _epanet2.EN_PERIODS
EN_NODECOUNT = _epanet2.EN_NODECOUNT
EN_TANKCOUNT = _epanet2.EN_TANKCOUNT
EN_LINKCOUNT = _epanet2.EN_LINKCOUNT
EN_PATCOUNT = _epanet2.EN_PATCOUNT
EN_CURVECOUNT = _epanet2.EN_CURVECOUNT
EN_CONTROLCOUNT = _epanet2.EN_CONTROLCOUNT
EN_JUNCTION = _epanet2.EN_JUNCTION
EN_RESERVOIR = _epanet2.EN_RESERVOIR
EN_TANK = _epanet2.EN_TANK
EN_CVPIPE = _epanet2.EN_CVPIPE
EN_PIPE = _epanet2.EN_PIPE
EN_PUMP = _epanet2.EN_PUMP
EN_PRV = _epanet2.EN_PRV
EN_PSV = _epanet2.EN_PSV
EN_PBV = _epanet2.EN_PBV
EN_FCV = _epanet2.EN_FCV
EN_TCV = _epanet2.EN_TCV
EN_GPV = _epanet2.EN_GPV
EN_NONE = _epanet2.EN_NONE
EN_CHEM = _epanet2.EN_CHEM
EN_AGE = _epanet2.EN_AGE
EN_TRACE = _epanet2.EN_TRACE
EN_CONCEN = _epanet2.EN_CONCEN
EN_MASS = _epanet2.EN_MASS
EN_SETPOINT = _epanet2.EN_SETPOINT
EN_FLOWPACED = _epanet2.EN_FLOWPACED
EN_CFS = _epanet2.EN_CFS
EN_GPM = _epanet2.EN_GPM
EN_MGD = _epanet2.EN_MGD
EN_IMGD = _epanet2.EN_IMGD
EN_AFD = _epanet2.EN_AFD
EN_LPS = _epanet2.EN_LPS
EN_LPM = _epanet2.EN_LPM
EN_MLD = _epanet2.EN_MLD
EN_CMH = _epanet2.EN_CMH
EN_CMD = _epanet2.EN_CMD
EN_TRIALS = _epanet2.EN_TRIALS
EN_ACCURACY = _epanet2.EN_ACCURACY
EN_TOLERANCE = _epanet2.EN_TOLERANCE
EN_EMITEXPON = _epanet2.EN_EMITEXPON
EN_DEMANDMULT = _epanet2.EN_DEMANDMULT
EN_LOWLEVEL = _epanet2.EN_LOWLEVEL
EN_HILEVEL = _epanet2.EN_HILEVEL
EN_TIMER = _epanet2.EN_TIMER
EN_TIMEOFDAY = _epanet2.EN_TIMEOFDAY
EN_AVERAGE = _epanet2.EN_AVERAGE
EN_MINIMUM = _epanet2.EN_MINIMUM
EN_MAXIMUM = _epanet2.EN_MAXIMUM
EN_RANGE = _epanet2.EN_RANGE
EN_MIX1 = _epanet2.EN_MIX1
EN_MIX2 = _epanet2.EN_MIX2
EN_FIFO = _epanet2.EN_FIFO
EN_LIFO = _epanet2.EN_LIFO
EN_NOSAVE = _epanet2.EN_NOSAVE
EN_SAVE = _epanet2.EN_SAVE
EN_INITFLOW = _epanet2.EN_INITFLOW

def ENepanet(arg1, arg2, arg3, arg4):
    return _epanet2.ENepanet(arg1, arg2, arg3, arg4)
ENepanet = _epanet2.ENepanet

def ENopen(arg1, arg2, arg3):
    return _epanet2.ENopen(arg1, arg2, arg3)
ENopen = _epanet2.ENopen

def ENsaveinpfile(arg1):
    return _epanet2.ENsaveinpfile(arg1)
ENsaveinpfile = _epanet2.ENsaveinpfile

def ENclose():
    return _epanet2.ENclose()
ENclose = _epanet2.ENclose

def ENsolveH():
    return _epanet2.ENsolveH()
ENsolveH = _epanet2.ENsolveH

def ENsaveH():
    return _epanet2.ENsaveH()
ENsaveH = _epanet2.ENsaveH

def ENopenH():
    return _epanet2.ENopenH()
ENopenH = _epanet2.ENopenH

def ENinitH(arg1):
    return _epanet2.ENinitH(arg1)
ENinitH = _epanet2.ENinitH

def ENrunH():
    return _epanet2.ENrunH()
ENrunH = _epanet2.ENrunH

def ENnextH():
    return _epanet2.ENnextH()
ENnextH = _epanet2.ENnextH

def ENcloseH():
    return _epanet2.ENcloseH()
ENcloseH = _epanet2.ENcloseH

def ENsavehydfile(arg1):
    return _epanet2.ENsavehydfile(arg1)
ENsavehydfile = _epanet2.ENsavehydfile

def ENusehydfile(arg1):
    return _epanet2.ENusehydfile(arg1)
ENusehydfile = _epanet2.ENusehydfile

def ENsolveQ():
    return _epanet2.ENsolveQ()
ENsolveQ = _epanet2.ENsolveQ

def ENopenQ():
    return _epanet2.ENopenQ()
ENopenQ = _epanet2.ENopenQ

def ENinitQ(arg1):
    return _epanet2.ENinitQ(arg1)
ENinitQ = _epanet2.ENinitQ

def ENrunQ():
    return _epanet2.ENrunQ()
ENrunQ = _epanet2.ENrunQ

def ENnextQ():
    return _epanet2.ENnextQ()
ENnextQ = _epanet2.ENnextQ

def ENstepQ():
    return _epanet2.ENstepQ()
ENstepQ = _epanet2.ENstepQ

def ENcloseQ():
    return _epanet2.ENcloseQ()
ENcloseQ = _epanet2.ENcloseQ

def ENwriteline(arg1):
    return _epanet2.ENwriteline(arg1)
ENwriteline = _epanet2.ENwriteline

def ENreport():
    return _epanet2.ENreport()
ENreport = _epanet2.ENreport

def ENresetreport():
    return _epanet2.ENresetreport()
ENresetreport = _epanet2.ENresetreport

def ENsetreport(arg1):
    return _epanet2.ENsetreport(arg1)
ENsetreport = _epanet2.ENsetreport

def ENgetcontrol(arg1):
    return _epanet2.ENgetcontrol(arg1)
ENgetcontrol = _epanet2.ENgetcontrol

def ENgetcount(arg1):
    return _epanet2.ENgetcount(arg1)
ENgetcount = _epanet2.ENgetcount

def ENgetoption(arg1):
    return _epanet2.ENgetoption(arg1)
ENgetoption = _epanet2.ENgetoption

def ENgettimeparam(arg1):
    return _epanet2.ENgettimeparam(arg1)
ENgettimeparam = _epanet2.ENgettimeparam

def ENgetflowunits():
    return _epanet2.ENgetflowunits()
ENgetflowunits = _epanet2.ENgetflowunits

def ENgetpatternindex(arg1):
    return _epanet2.ENgetpatternindex(arg1)
ENgetpatternindex = _epanet2.ENgetpatternindex

def ENgetpatternid(arg1):
    return _epanet2.ENgetpatternid(arg1)
ENgetpatternid = _epanet2.ENgetpatternid

def ENgetpatternlen(arg1):
    return _epanet2.ENgetpatternlen(arg1)
ENgetpatternlen = _epanet2.ENgetpatternlen

def ENgetpatternvalue(arg1, arg2):
    return _epanet2.ENgetpatternvalue(arg1, arg2)
ENgetpatternvalue = _epanet2.ENgetpatternvalue

def ENgetqualtype():
    return _epanet2.ENgetqualtype()
ENgetqualtype = _epanet2.ENgetqualtype

def ENgeterror(arg1, arg3):
    return _epanet2.ENgeterror(arg1, arg3)
ENgeterror = _epanet2.ENgeterror

def ENgetnodeindex(arg1):
    return _epanet2.ENgetnodeindex(arg1)
ENgetnodeindex = _epanet2.ENgetnodeindex

def ENgetnodeid(arg1):
    return _epanet2.ENgetnodeid(arg1)
ENgetnodeid = _epanet2.ENgetnodeid

def ENgetnodetype(arg1):
    return _epanet2.ENgetnodetype(arg1)
ENgetnodetype = _epanet2.ENgetnodetype

def ENgetnodevalue(arg1, arg2):
    return _epanet2.ENgetnodevalue(arg1, arg2)
ENgetnodevalue = _epanet2.ENgetnodevalue

def ENgetlinkindex(arg1):
    return _epanet2.ENgetlinkindex(arg1)
ENgetlinkindex = _epanet2.ENgetlinkindex

def ENgetlinkid(arg1):
    return _epanet2.ENgetlinkid(arg1)
ENgetlinkid = _epanet2.ENgetlinkid

def ENgetlinktype(arg1):
    return _epanet2.ENgetlinktype(arg1)
ENgetlinktype = _epanet2.ENgetlinktype

def ENgetlinknodes(arg1):
    return _epanet2.ENgetlinknodes(arg1)
ENgetlinknodes = _epanet2.ENgetlinknodes

def ENgetlinkvalue(arg1, arg2):
    return _epanet2.ENgetlinkvalue(arg1, arg2)
ENgetlinkvalue = _epanet2.ENgetlinkvalue

def ENgetversion():
    return _epanet2.ENgetversion()
ENgetversion = _epanet2.ENgetversion

def ENsetcontrol(arg1, arg2, arg3, arg4, arg5, arg6):
    return _epanet2.ENsetcontrol(arg1, arg2, arg3, arg4, arg5, arg6)
ENsetcontrol = _epanet2.ENsetcontrol

def ENsetnodevalue(arg1, arg2, arg3):
    return _epanet2.ENsetnodevalue(arg1, arg2, arg3)
ENsetnodevalue = _epanet2.ENsetnodevalue

def ENsetlinkvalue(arg1, arg2, arg3):
    return _epanet2.ENsetlinkvalue(arg1, arg2, arg3)
ENsetlinkvalue = _epanet2.ENsetlinkvalue

def ENaddpattern(arg1):
    return _epanet2.ENaddpattern(arg1)
ENaddpattern = _epanet2.ENaddpattern

def ENsetpattern(arg1, floatarray, nfloats):
    return _epanet2.ENsetpattern(arg1, floatarray, nfloats)
ENsetpattern = _epanet2.ENsetpattern

def ENsetpatternvalue(arg1, arg2, arg3):
    return _epanet2.ENsetpatternvalue(arg1, arg2, arg3)
ENsetpatternvalue = _epanet2.ENsetpatternvalue

def ENsettimeparam(arg1, arg2):
    return _epanet2.ENsettimeparam(arg1, arg2)
ENsettimeparam = _epanet2.ENsettimeparam

def ENsetoption(arg1, arg2):
    return _epanet2.ENsetoption(arg1, arg2)
ENsetoption = _epanet2.ENsetoption

def ENsetstatusreport(arg1):
    return _epanet2.ENsetstatusreport(arg1)
ENsetstatusreport = _epanet2.ENsetstatusreport

def ENsetqualtype(arg1, arg2, arg3, arg4):
    return _epanet2.ENsetqualtype(arg1, arg2, arg3, arg4)
ENsetqualtype = _epanet2.ENsetqualtype
WRAPPER_ERROR_FILE_OPEN = _epanet2.WRAPPER_ERROR_FILE_OPEN
WRAPPER_ERROR_NOT_IMPLEMENTED = _epanet2.WRAPPER_ERROR_NOT_IMPLEMENTED

def ENsetpatterndim(index, dim):
    return _epanet2.ENsetpatterndim(index, dim)
ENsetpatterndim = _epanet2.ENsetpatterndim

def ENsetpatterndim_wrap(index, dim):
    return _epanet2.ENsetpatterndim_wrap(index, dim)
ENsetpatterndim_wrap = _epanet2.ENsetpatterndim_wrap
# This file is compatible with both classic and new-style classes.

cvar = _epanet2.cvar

